"""
data_loader.py
--------------
Loads and caches the MandiFlow integrated dataset.
All heavy I/O is wrapped with st.cache_data to avoid
re-running on every page interaction.
"""

import os
import numpy as np
import pandas as pd
import streamlit as st

# ── Path resolution ────────────────────────────────────────────────────────────
_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATASET_PATH = os.path.join(_ROOT, "Datasets", "Cleaned", "final_integrated_dataset.csv")

# Columns that should be numeric
_NUMERIC_COLS = [
    "arrival_quantity",
    "arrival_quantity_qtl",
    "farmer_count",
    "modal_price",
    "msp",
    "avg_temperature_c",
    "total_rainfall_mm",
    "avg_humidity_percent",
    "avg_distance_km",
    "avg_transit_hours",
    "avg_speed_kmph",
    "transit_delay_rate",
]


@st.cache_data(show_spinner=False)
def load_data() -> pd.DataFrame:
    """
    Load the cleaned integrated mandi dataset.
    Returns a fully typed, clean DataFrame ready for analytics.
    """
    if not os.path.exists(DATASET_PATH):
        st.error(
            f"Dataset not found at: `{DATASET_PATH}`  \n"
            "Please ensure the cleaned dataset has been generated by the project pipeline."
        )
        st.stop()

    df = pd.read_csv(DATASET_PATH, low_memory=False)

    # ── Date parsing ──────────────────────────────────────────────────────────
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    # ── Numeric coercion ──────────────────────────────────────────────────────
    for col in _NUMERIC_COLS:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype(str)
                .str.extract(r"([-+]?\d*\.?\d+)")[0]
            )
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # ── Derived / cleaned columns ──────────────────────────────────────────────
    if "avg_transit_hours" in df.columns:
        df["transit_hours_clean"] = df["avg_transit_hours"].copy()
        df.loc[df["transit_hours_clean"] < 0, "transit_hours_clean"] = np.nan
        df.loc[df["transit_hours_clean"] > 168, "transit_hours_clean"] = np.nan

    if "transit_hours_clean" in df.columns:
        df["long_transit_flag"] = df["transit_hours_clean"] > 24

    if "modal_price" in df.columns and "msp" in df.columns:
        valid_price_mask = df["modal_price"].notna() & df["msp"].notna() & (df["msp"] > 0)
        df["price_vs_msp"] = np.where(
            valid_price_mask, df["modal_price"] - df["msp"], np.nan
        )
        df["price_vs_msp_pct"] = np.where(
            valid_price_mask,
            (df["modal_price"] - df["msp"]) / df["msp"] * 100,
            np.nan,
        )
        df["price_crash"] = np.where(
            valid_price_mask, df["modal_price"] < df["msp"], np.nan
        )

    for col in ["crop_name", "mandi_name", "district", "mandi_type"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace("nan", np.nan)

    key_cols = [c for c in ["modal_price", "arrival_quantity_qtl"] if c in df.columns]
    if key_cols:
        df = df.dropna(subset=key_cols, how="all")

    df = df.reset_index(drop=True)
    return df


@st.cache_data(show_spinner=False)
def get_filter_options(df: pd.DataFrame) -> dict:
    """Return sorted unique values for each filterable dimension."""
    opts = {}

    for col in ["crop_name", "district", "mandi_name", "mandi_id"]:
        if col in df.columns:
            vals = sorted(df[col].dropna().unique().tolist())
            opts[col] = vals

    if "warehouse_name" in df.columns:
        opts["warehouse"] = sorted(df["warehouse_name"].dropna().unique().tolist())
    elif "mandi_name" in df.columns:
        if "avg_transit_hours" in df.columns:
            opts["warehouse"] = sorted(
                df[df["avg_transit_hours"].notna()]["mandi_name"].dropna().unique().tolist()
            )
        else:
            opts["warehouse"] = opts.get("mandi_name", [])

    if "date" in df.columns:
        valid_dates = df["date"].dropna()
        if len(valid_dates) > 0:
            opts["date_min"] = valid_dates.min().date()
            opts["date_max"] = valid_dates.max().date()

    return opts
